# Container image for a custom toolbox container based on Red Hat UBI 8.7
FROM registry.access.redhat.com/ubi8/ubi:8.7

ENV NAME=rhel-toolbox VERSION=ubi8.7
LABEL com.github.containers.toolbox="true" \
      com.redhat.component="$NAME" \
      name="$NAME" \
      version="$VERSION" \
      usage="This image is meant to be used with the toolbox command" \
      summary="Base image for creating RHEL toolbox containers"

RUN sed -i '/tsflags=nodocs/d' /etc/dnf/dnf.conf &&\
    dnf -y swap coreutils-single coreutils-full &&\
    dnf -y reinstall \
        acl \
        bash \
        curl \
        gawk \
        grep \
        gzip \
        libcap \
        openssl \
        p11-kit \
        pam \
        python3 \
        rpm \
        sed \
        systemd \
        tar &&\
    dnf -y install \
        bash-completion \
        bc \
        bzip2 \
        diffutils \
        dnf-plugins-core \
        findutils \
        flatpak-spawn \
        git \
        glibc-all-langpacks \
        gnupg \
        gnupg2-smime \
        hostname \
        iproute \
        iputils \
        krb5-libs \
        less \
        lsof \
        man-db \
        openssh-clients \
        passwd \
        pigz \
        procps-ng \
        rsync \
        shadow-utils \
        sudo \
        time \
        unzip \
        util-linux \
        vte-profile \
        wget \
        which \
        xorg-x11-xauth \
        xz \
        zip &&\
    dnf clean all &&\
    rm -rf /var/cache/{dnf,yum} &&\
    rm -rf /var/lib/dnf/history.* &&\
    rm -rf /var/log/*
