FROM registry.access.redhat.com/ubi8/ubi:8.6

ENV NAME=rhel-toolbox \
    VERSION=ubi8.6

LABEL com.github.containers.toolbox="true" \
      com.redhat.component="$NAME" \
      name="$NAME" \
      version="$VERSION" \
      usage="This image is meant to be used with the toolbox command" \
      summary="Base image for creating RHEL toolbox containers" \
      maintainer="Caseraw <https://github.com/Caseraw>"

RUN dnf install -y \
    python39 \
    vim \
    git \
    less \
    git \
    curl \
    wget \
    rsync \
    jq \
    bash-completion \
    bc \
    bzip2 \
    zip \
    xz \
    unzip \
    diffutils \
    dnf-plugins-core \
    findutils \
    flatpak-spawn \
    glibc-all-langpacks \
    gnupg \
    gnupg2-smime \
    hostname \
    iproute \
    iputils \
    krb5-libs \
    lsof \
    bind-utils \
    man-db \
    openssh \
    openssh-clients \
    passwd \
    pigz \
    procps-ng \
    shadow-utils \
    sudo \
    time \
    util-linux \
    vte-profile \
    which \
    xorg-x11-xauth &&\
    dnf clean all &&\
    rm -rf /var/cache/{dnf,yum} &&\
    rm -rf /var/lib/dnf/history.* &&\
    rm -rf /var/log/*

RUN pip3 install --upgrade \
    pip \
    setuptools \
    bpython
